%YAML:1.0

# This file lists paths of all other configuration files.
# Modify these paths according to your specific machine.

control_setting:"/home/zc/catkin_car/src/vinsrobot/config/control_setting.yaml"

orb_setting_320:"/home/zc/catkin_car/src/vinsrobot/config/orb_setting_320.yaml"

orb_setting_640:"/home/zc/catkin_car/src/vinsrobot/config/orb_setting_640.yaml"

sensor_setting:"/home/zc/catkin_car/src/vinsrobot/config/sensor_setting.yaml"
